import json
import sys
from pathlib import Path
from typing import Any, Type

from pydantic import BaseModel
from shared.schemas.project import DashboardStats, Project, ProjectCreate, ProjectUpdate
from shared.schemas.scene import Scene, SceneCreate
from shared.schemas.render_job import RenderJob

def pydantic_to_ts(model: Type[BaseModel]) -> str:
    schema = model.model_json_schema()
    name = schema.get("title", model.__name__)
    lines = [f"export interface {name} {{"]
    
    properties = schema.get("properties", {})
    required = schema.get("required", [])
    
    for prop_name, prop_data in properties.items():
        ts_type = map_type(prop_data)
        is_optional = prop_name not in required
        lines.append(f"  {prop_name}{'?' if is_optional else ''}: {ts_type};")
        
    lines.append("}")
    return "\n".join(lines)

def map_type(prop_data: dict[str, Any]) -> str:
    if "anyOf" in prop_data:
        types = [map_type(t) for t in prop_data["anyOf"] if t.get("type") != "null"]
        if any(t.get("type") == "null" for t in prop_data["anyOf"]):
            return " | ".join(types) + " | null"
        return " | ".join(types)

    ptype = prop_data.get("type")
    format = prop_data.get("format")
    
    if ptype == "string":
        if format == "uuid":
            return "string"
        if format == "date-time":
            return "string"
        return "string"
    if ptype == "integer" or ptype == "number":
        return "number"
    if ptype == "boolean":
        return "boolean"
    if ptype == "array":
        items = prop_data.get("items", {})
        return f"{map_type(items)}[]"
    if ptype == "object":
        return "Record<string, any>"
    
    return "any"

def main():
    models = [
        Project, ProjectCreate, ProjectUpdate, DashboardStats,
        Scene, SceneCreate,
        RenderJob
    ]
    
    output_path = Path(__file__).parent.parent.parent / "frontend" / "src/types/contracts.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    content = ["// Auto-generated by backend/scripts/generate_ts_types.py", ""]
    for model in models:
        content.append(pydantic_to_ts(model))
        content.append("")
        
    with open(output_path, "w") as f:
        f.write("\n".join(content))
    
    print(f"Generated TS types to {output_path}")

if __name__ == "__main__":
    main()
