// Auto-generated by backend/scripts/generate_ts_types.py

export interface Project {
  id: string;
  user_id: string;
  title: string;
  description?: string | null;
  source_language?: string;
  target_scenes?: number | null;
  config?: Record<string, any>;
  status?: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectCreate {
  title: string;
  description?: string | null;
  source_language?: string;
  target_scenes?: number | null;
  use_primitives?: boolean;
  config?: Record<string, any> | null;
}

export interface ProjectUpdate {
  title?: string | null;
  description?: string | null;
  source_language?: string | null;
  target_scenes?: number | null;
  status?: string | null;
  config?: Record<string, any> | null;
}

export interface DashboardStats {
  total_projects: number;
  active_jobs: number;
  total_tokens_used: number;
  total_render_time_hours: number;
}

export interface Scene {
  id: string;
  project_id: string;
  scene_order: number;
  storyboard_status?: string;
  storyboard_text?: string | null;
  voice_script?: string | null;
  planner_output?: Record<string, any> | any[] | null;
  sync_segments?: Record<string, any> | any[] | null;
  manim_code?: string | null;
  manim_code_version?: number;
  audio_url?: string | null;
  timestamps?: Record<string, any> | any[] | null;
  duration_seconds?: number | string | null;
  plan_status?: string;
  voice_script_status?: string;
  review_loop_status?: string;
  created_at?: string;
  updated_at?: string;
}

export interface SceneCreate {
  scene_order: number;
  storyboard_text?: string | null;
  voice_script?: string | null;
}

export interface RenderJob {
  id: string;
  project_id: string;
  scene_id?: string | null;
  job_type: string;
  render_quality?: string | null;
  status?: string;
  progress?: number;
  logs?: string | null;
  asset_url?: string | null;
  error_code?: string | null;
  webhook_url?: string | null;
  docker_image_tag?: string | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  metadata?: Record<string, any>;
}
