-- NON-DEPLOYABLE COMPATIBILITY MARKER
-- ===================================
--
-- This path used to contain a hand-maintained "consolidated" schema. It drifted
-- from the ordered migrations and could not safely initialize or upgrade a
-- database. It remains as a marker because older tooling references the path.
--
-- `backend/supabase/migrations/*.sql` is the only deployable source of truth.
-- Apply it with the Supabase CLI, or validate a clean PostgreSQL 17 replay with:
--
--   bash backend/supabase/validate_migrations.sh
--
-- When a review snapshot is needed, generate it from a freshly reset local
-- Supabase database; never edit or deploy the generated output:
--
--   cd backend
--   supabase db reset
--   supabase db dump --local --schema public > /tmp/manim-public-schema.sql
--
-- Do not add executable SQL to this file.
