bind 127.0.0.1
protected-mode yes
port 6379
daemonize no
supervised no
pidfile /tmp/redis.pid
dir /data/redis

appendonly yes
appendfsync everysec
save 60 1000
maxmemory-policy noeviction

loglevel notice
logfile ""
